### ISSUE TITLE
config2spec TODO

### ISSUE THREAD

**Issue by encukou** [befeleme/pyp2spec#2]
MVP:
* [x] Flat config structure 
* [x] Type checking config values
* [x] Put `expected` in test directory name

---

later:
* [ ] Exclude requirements (sed in prep?)
* [ ] Run mockbuild on results
* [ ] Document config fields

**Comment by papoteur-mga** [comment]
Hello,
Can you provide an option to choose the template, either on the CLI or in in a user's config file (preferred)?
I use this great application for Mageia, but I have to change some configuration in the same way each time I use it.
